apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: hiendinh3010/client
    context: client
    sync:
      manual:
      - src: src/**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: hiendinh3010/comments
    context: comments
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: hiendinh3010/event-bus
    context: event-bus
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: hiendinh3010/moderation
    context: moderation
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: hiendinh3010/posts
    context: posts
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: hiendinh3010/query
    context: query
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*